categorias:
  - Argentina
  - España
  - Deportes
  - Noticias
  - Cine
  - Series y entretenimiento
  - Infantiles
  - Documentales y cultura
  - Música
  - Radios
  - Religión
  - Estilo de vida
  - Canales FAST
