# Palabras clave a INCLUIR (solo estos canales serán incluidos)
allowed_keywords:
  - argentina
  - españa
  - spain

# Palabras clave a EXCLUIR (se aplicarán después de las palabras clave permitidas)
blocked_keywords: []
